# Generated by Django 4.0.5 on 2022-06-19 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='brands/')),
            ],
            options={
                'db_table': 'brand',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='categories/')),
            ],
            options={
                'db_table': 'category',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='cars/')),
                ('doors', models.IntegerField(default=4)),
                ('seats', models.IntegerField(default=4)),
                ('buggage', models.IntegerField()),
                ('transmission', models.IntegerField(choices=[(1, 'Auto'), (2, 'Manual')], default=1)),
                ('conditioner', models.BooleanField(default=False)),
                ('fuel', models.CharField(max_length=255)),
                ('insurance', models.FloatField()),
                ('price', models.FloatField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.category')),
            ],
            options={
                'db_table': 'car',
                'ordering': ['id'],
            },
        ),
    ]
