# Generated by Django 4.0.5 on 2022-06-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fullname',
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(default='unknown', max_length=254),
        ),
    ]
