# Generated by Django 4.0.5 on 2022-06-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_fullname_order_name_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='from_time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='to_time',
            field=models.DateField(null=True),
        ),
    ]
